if("scrollRestoration" in history)history.scrollRestoration="manual";
window.addEventListener("load",()=>{if(location.hash)history.replaceState(null,"",location.pathname+location.search);window.scrollTo({top:0,left:0,behavior:"instant"})},{once:true});
let lang=localStorage.getItem("vl-lang")||"fr",current=null,currentVersion="original";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],cfg=window.VICHY_CONFIG||{},backendLikes={};
const monthIndex={janvier:0,january:0,fevrier:1,february:1,mars:2,march:2,avril:3,april:3,mai:4,may:4,juin:5,june:5,juillet:6,july:6,aout:7,august:7,septembre:8,september:8,octobre:9,october:9,novembre:10,november:10,decembre:11,december:11};
const dateValue=value=>{const text=String(value||"").trim(),iso=Date.parse(text);if(Number.isFinite(iso))return iso;const parts=text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().match(/(\d{1,2})\s+([a-z]+)\s+(\d{4})/);return parts&&monthIndex[parts[2]]!==undefined?Date.UTC(+parts[3],monthIndex[parts[2]],+parts[1]):0};
const texts=(Array.isArray(window.VICHY_TEXTS)?[...window.VICHY_TEXTS]:[]).sort((a,b)=>dateValue(b.date)-dateValue(a.date));
const liked=new Set(JSON.parse(localStorage.getItem("vl-liked")||"[]")),visitorId=localStorage.getItem("vl-visitor")||crypto.randomUUID();
localStorage.setItem("vl-visitor",visitorId);
const configured=()=>cfg.supabaseUrl&&!cfg.supabaseUrl.includes("YOUR_PROJECT")&&cfg.supabaseAnonKey&&!cfg.supabaseAnonKey.includes("YOUR_SUPABASE");
const headers=()=>({apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`,"Content-Type":"application/json"});
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const categoryNames={prose:{fr:"Prose",en:"Prose"},poem:{fr:"Poème",en:"Poem"},letter:{fr:"Lettre",en:"Letter"},memory:{fr:"Souvenir de Vichy",en:"Memory of Vichy"},note:{fr:"Note",en:"Note"},other:{fr:"Autre",en:"Other"}};
const categoryMarkup=x=>{const items=(Array.isArray(x.categories)?x.categories:[]).map(key=>categoryNames[key]?.[lang]||key);return items.length?`<div class="card-categories">${items.map(item=>`<span>${esc(item)}</span>`).join("")}</div>`:""};
const original=x=>x.original||x[x.originalLang||"fr"]||x.fr||x.en;
function excerpt(value){const clean=String(value).replace(/\s+/g," ").trim(),parts=clean.match(/[^.!?…]+[.!?…]+|[^.!?…]+$/g)||[clean];return parts.slice(0,2).join(" ").trim().replace(/[.…]+$/,"")+"…"}
function count(x){const value=backendLikes[x.id]??x.likes??0;return Number.isFinite(Number(value))?Number(value):0}
function card(x,i){return `<article class="card" data-id="${esc(x.id)}"><div class="card-top"><time>${esc(x.date)}</time><span class="heart">♡ ${count(x)}</span></div><div class="image"><img src="${esc(x.image||"")}" alt="" onerror="this.hidden=true"><span>IMAGE ${String(i+1).padStart(2,"0")}</span></div><p>«${esc(excerpt(original(x)))}»</p><div class="translation-choice"><button data-version="fr" data-id="${esc(x.id)}">FR · Lire</button><button data-version="en" data-id="${esc(x.id)}">EN · Read</button></div>${categoryMarkup(x)}<footer>${esc(x.author)}<small>${esc(x.place)}</small></footer></article>`}
function updateFileName(){const file=$("#documentInput")?.files?.[0];$("#fileName").textContent=file?file.name:(lang==="fr"?"Aucun fichier sélectionné":"No file selected")}
function render(){const html=texts.slice(0,6).map(card).join("");$("#lettersGrid").innerHTML=html;$("#archiveGrid").innerHTML=texts.map(card).join("");bindCards();$$("[data-fr]").forEach(el=>el.textContent=el.dataset[lang]);$$("[data-placeholder-fr]").forEach(el=>el.placeholder=lang==="fr"?el.dataset.placeholderFr:el.dataset.placeholderEn);$("#submitOpen").textContent=lang==="fr"?"Envoyer texte":"Submit text";document.documentElement.lang=lang;$$("[data-lang]").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));updateFileName()}
function bindCards(){$$(".card").forEach(el=>el.onclick=e=>{if(e.target.closest(".translation-choice"))return;openLetter(texts.find(x=>x.id===el.dataset.id),"original")});$$(".translation-choice button").forEach(b=>b.onclick=e=>{e.stopPropagation();openLetter(texts.find(x=>x.id===b.dataset.id),b.dataset.version)})}
function openLetter(x,version="original"){current=x;currentVersion=version;const body=version==="original"?original(x):(x[version]||original(x)),image=$("#fullImage");$("#fullDate").textContent=x.date;image.hidden=!x.image;image.src=x.image||"";image.alt=x.image?`${x.author} — Vichy Littéraire`:"";image.onerror=()=>{image.hidden=true};$("#fullBody").innerHTML=String(body).split(/\n+/).map(p=>`<p>${esc(p)}</p>`).join("");$("#fullAuthor").innerHTML=`<b>— ${esc(x.author)}</b><br><span>${esc(x.place)}</span>`;updateLike();show("#letterModal")}
function updateLike(){$("#likeButton").innerHTML=`${liked.has(current.id)?"♥":"♡"} ${count(current)}<small>${lang==="fr"?"cette lettre m’a touché":"this letter moved me"}</small>`;$("#likeButton").disabled=liked.has(current.id)}
function show(id){$(id).hidden=false;document.body.classList.add("locked")}function hide(el){el.closest(".overlay").hidden=true;if(!$$(".overlay:not([hidden])").length)document.body.classList.remove("locked")}
function resetSubmitModal(){const form=$("#submitForm"),success=$("#success");form.reset();form.hidden=false;success.hidden=true;success.textContent="";updateFileName()}
$$("[data-close]").forEach(b=>b.onclick=()=>hide(b));$("#archiveOpen").onclick=$("#archiveOpenBottom").onclick=()=>show("#archiveModal");$("#submitOpen").onclick=()=>{resetSubmitModal();show("#submitModal")};
$("#likeButton").onclick=async()=>{if(!current||liked.has(current.id))return;if(!configured()){alert(lang==="fr"?"Supabase n’est pas encore connecté.":"Supabase is not connected yet.");return}$("#likeButton").disabled=true;try{const r=await fetch(`${cfg.supabaseUrl}/rest/v1/rpc/like_letter`,{method:"POST",headers:headers(),body:JSON.stringify({target_letter_id:current.id,target_visitor_id:visitorId})});if(!r.ok)throw new Error();backendLikes[current.id]=Number(await r.json());liked.add(current.id);localStorage.setItem("vl-liked",JSON.stringify([...liked]));updateLike();render()}catch{alert(lang==="fr"?"Le vote n’a pas été enregistré.":"The like could not be saved.");$("#likeButton").disabled=false}};
$$("[data-lang]").forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem("vl-lang",lang);render();if(current)openLetter(current,currentVersion)});
$("#documentInput").onchange=updateFileName;
$("#submitForm").onsubmit=async e=>{e.preventDefault();if(!e.target.querySelector('input[name="category"]:checked')){alert(lang==="fr"?"Choisissez au moins un type de texte. Vous pouvez en sélectionner plusieurs.":"Choose at least one type of text. You may select several.");return}if(!configured()){alert(lang==="fr"?"Supabase n’est pas encore connecté.":"Supabase is not connected yet.");return}const form=e.target,button=form.querySelector('button[type="submit"]'),f=new FormData(form),location=String(f.get("location")||"").trim(),locationParts=location.split(","),city=(locationParts.shift()||location).trim(),country=(locationParts.join(",").trim()||"—"),documentFile=f.get("document"),hasText=String(f.get("body")||"").trim().length>=20,hasDocument=documentFile instanceof File&&documentFile.size>0;if(!hasText&&!hasDocument){alert(lang==="fr"?"Écrivez un texte ou joignez un document.":"Write a text or attach a document.");return}if(hasDocument&&documentFile.size>5242880){alert("5 MB max");return}f.set("city",city);f.set("country",country);f.delete("location");f.set("website","");button.disabled=true;button.textContent=lang==="fr"?"Envoi…":"Sending…";try{const response=await fetch(`${cfg.supabaseUrl}/functions/v1/send-letter`,{method:"POST",headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`},body:f});if(!response.ok)throw new Error();form.reset();form.hidden=true;$("#success").hidden=false;$("#success").textContent=lang==="fr"?"Merci. Votre lettre a été envoyée à Vichy Littéraire et sera publiée prochainement.":"Thank you. Your letter has been sent to Vichy Littéraire and will be published soon."}catch{$("#success").hidden=false;$("#success").textContent=lang==="fr"?"L’envoi n’a pas abouti. Veuillez réessayer.":"The message could not be sent. Please try again."}finally{button.disabled=false;button.textContent=lang==="fr"?"Envoyer le texte":"Submit text"}};
async function loadLikes(){if(!configured())return;try{const r=await fetch(`${cfg.supabaseUrl}/rest/v1/rpc/get_letter_likes`,{method:"POST",headers:headers(),body:JSON.stringify({letter_ids:texts.map(x=>x.id)})});if(!r.ok)return;(await r.json()).forEach(row=>backendLikes[row.letter_id]=Number(row.likes_count));render()}catch{}}
render();loadLikes();
